### PR TITLE
Add required permissions to README examples

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by fkirc** [comment]
Can you provide some background why this is needed? It seems to be lots of boilerplate if everybody needs to copypast additional lines.

**Comment by Maks3w** [comment]
This is needed when you take a safe/lower_privilege approach on your organization/repo and GITHUB_TOKEN only has read only privileges

**Comment by paescuj** [comment]
Maybe we could add this commented out in the README

**Comment by Maks3w** [comment]
IMO GitHub is pivoting to a less privileged environment step by step.

The mission should be assist and help repositories maintainers in having a safer execution environment.

**Comment by paescuj** [comment]
> IMO GitHub is pivoting to a less privileged environment step by step.
> 
> The mission should be assist and help repositories maintainers in having a safer execution environment.

Any official sources for this? (Just curious 😄)
Of course, I'm all in for less privileged environments! I still think it would be the best to add this as a comment so user of this action are aware of it but can choose for themselves whether they want set this option or not.

**Comment by fkirc** [comment]
I could imagine that declaring permissions is good for entire jobs, but I don’t like it for individual steps.
I know that some users are using dozens of skip-duplicate-action-steps within a single yaml-file, so it would be a significant overhead to add those lines everywhere.

To be honest, I believe that permissions might be better located within the action.yaml in this repo instead of burdening individual users with permissions.

**Comment by joelossher** [comment]
+1 to the idea of documenting the minimum permissions needed somewhere. I just hit this issue and was grateful to see that this PR indicated which were needed.

**Comment by paescuj** [comment]
Addressed in #192.

Thanks @Maks3w, @fkirc, @joelossher!

**Pull request closed without merging**
